### ISSUE TITLE
big queryのnul値の出力が文字列のnullになる

### ISSUE THREAD

**Issue by kawaguchi-yasutaka** [myuon/gallon#20]
## 期待していたこと
inにmysqlの値がnullだった場合、outのbig queryの値はnullになる
スクショ
![Image](https://github.com/user-attachments/assets/b1fb8108-544d-4a55-89de-d4f9f30067fc)

## 実際の動作
inにmysqlの値がnullだった場合、outのbig queryの値が文字列の`null`という文字列になりました。
スクショ
![Image](https://github.com/user-attachments/assets/9e120dbf-e5db-46a5-8570-fb02b7a3a299)

### ymlの例
```
in:
  type: sql
  driver: mysql
  table: test_tables
  schema:
    nullable_calumn:
      type: string
out:
  type: bigquery
  location: 
  projectId: 
  datasetId: 
  mode: replace
  tableId: test_tables
  schema:
    nullable_calumn:
      type: string
```
